name: Node CI

on: [push]

jobs:
  build:
    strategy:
      matrix:
        node-version: [12.x, 14.x]
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm restore, build & test
      run: |
        npm link --loglevel error
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Prepare for instapack full-cycle tests
      run: |
        npm install -g rimraf
        rimraf node_modules
        npm install --production --loglevel error
    - name: instapack full-cycle test - Vue 2
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new vue2
        ipack -d --no-sourcemaps
        ipack 
    - name: instapack full-cycle test - Vue 3
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new vue
        ipack -d --no-sourcemaps
        ipack 
    - name: instapack full-cycle test - React
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new react
        ipack -d --no-sourcemaps
        ipack 
    - name: instapack full-cycle test - Blazor
      run: |
        rimraf ./demo
        mkdir demo
        cd demo
        ipack new blazor
        ipack -d --no-sourcemaps
        ipack 
